code tidyup

diff --git a/download-rpms b/download-rpms
--- a/download-rpms
+++ b/download-rpms
@@ -1,5 +1,10 @@
 #!/bin/ksh
 
+# Not used but left as an example.
+# Only looks at release versions in package cloud so is inferior to adding the repos into yum's config
+
+PATH=/scripts:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH
+
 SCRIPTNAME=$0
 SCRIPTDIR=$(dirname "$SCRIPTNAME")
 VERSIONFILE=$SCRIPTDIR/tyk-versions.list
@@ -11,8 +16,7 @@ function help {
   echo "        -h print this help"
 }
 
-if [[ $# -lt 1 ]]
-then
+if [[ $# -lt 1 ]]; then
   help
   exit 1
 fi
@@ -24,8 +28,13 @@ typeset -A PUMP
 typeset -A SYNC
 
 function loadVersions {
-  typeset line; typeset IFS; typeset gwVers; typeset dshbVers; typeset pumpVers
-  typeset TIBvers; typeset syncVers
+  typeset line
+  typeset IFS
+  typeset gwVers
+  typeset dshbVers
+  typeset pumpVers
+  typeset TIBvers
+  typeset syncVers
   line=$1
   IFS=,
   echo "$line" | read version gwVers dshbVers pumpVers TIBvers syncVers
@@ -38,16 +47,14 @@ function loadVersions {
 
 function loadVersionFile {
   typeset line
-  for line in $(awk 'NF && !/#/' $VERSIONFILE)
-  do
+  for line in $(awk 'NF && !/#/' $VERSIONFILE); do
     loadVersions "$line"
   done
 }
 
 function listversions {
   typeset gwVersion
-  for version in $(echo ${!GATEWAY[@]} | xargs -n 1 | sort -rV)
-  do
+  for version in $(echo ${!GATEWAY[@]} | xargs -n 1 | sort -rV); do
     gwVersion=${GATEWAY[$version]}
     echo "Version:   $version"
     echo "    Gateway:   $gwVersion"
@@ -61,11 +68,9 @@ function download {
   typeset rpm=$1
   typeset url=$2
   echo "[INFO]Downloading $rpm from $url"
-  if [[ ! -f $rpm ]]
-  then
+  if [[ ! -f $rpm ]]; then
     curl -sL $url --output $rpm
-    if [[ $? -gt 0 ]]
-    then
+    if [[ $? -gt 0 ]]; then
       rm $rpm
       echo "[WARN]Failed to pull $rpm"
     else
@@ -78,33 +83,31 @@ function download {
 
 loadVersionFile
 
-while getopts :g:hl arg
-do
+while getopts :g:hl arg; do
   case $arg in
-    l)
-      listversions
-      exit 0
-      ;;
-    g)
-      version=$OPTARG
-      ;;
-    h)
-      help
-      exit 0;
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument."
-      exit 1
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG"
-      exit 1
-      ;;
+  l)
+    listversions
+    exit 0
+    ;;
+  g)
+    version=$OPTARG
+    ;;
+  h)
+    help
+    exit 0
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument."
+    exit 1
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG"
+    exit 1
+    ;;
   esac
 done
 
-if [[ ${GATEWAY[$version]+_} ]]
-then
+if [[ ${GATEWAY[$version]+_} ]]; then
   tykVersion=${GATEWAY[$version]}
   dshbVersion=${DASHBOARD[$tykVersion]}
   tibVersion=${TIB[$tykVersion]}
@@ -115,29 +118,25 @@ else
   exit 1
 fi
 
-if [[ -n $tykVersion ]]
-then
+if [[ -n $tykVersion ]]; then
   rpm="tyk-gateway-$tykVersion.x86_64.rpm"
   url="https://packagecloud.io/tyk/tyk-gateway/packages/el/7/$rpm/download.rpm"
   download $rpm $url
 fi
 
-if [[ -n $dshbVersion ]]
-then
+if [[ -n $dshbVersion ]]; then
   rpm="tyk-dashboard-$dshbVersion.x86_64.rpm"
   url="https://packagecloud.io/tyk/tyk-dashboard/packages/el/7/$rpm/download.rpm"
   download $rpm $url
 fi
 
-if [[ -n $tibVersion ]]
-then
+if [[ -n $tibVersion ]]; then
   rpm="tyk-identity-broker-$tibVersion.x86_64.rpm"
   url="https://packagecloud.io/tyk/tyk-identity-broker/packages/el/7/$rpm/download.rpm"
   download $rpm $url
 fi
 
-if [[ -n $pumpVersion ]]
-then
+if [[ -n $pumpVersion ]]; then
   rpm="tyk-pump-$pumpVersion.x86_64.rpm"
   url="https://packagecloud.io/tyk/tyk-pump/packages/el/7/$rpm/download.rpm"
   download $rpm $url
diff --git a/sbctl b/sbctl
--- a/sbctl
+++ b/sbctl
@@ -9,7 +9,10 @@ TIBBasePort=4001
 GatewayBasePort=5001
 RedisBasePort=6001
 MongoBasePort=7001
-SCRIPTDIR=$(cd $(dirname $SCRIPTNAME);echo $PWD)
+SCRIPTDIR=$(
+	cd $(dirname $SCRIPTNAME)
+	echo $PWD
+)
 VERSIONFILE=$SCRIPTDIR/tyk-versions.list
 
 # directories shared into all sandboxes to allow for plugins and certs to be installed easily
@@ -23,12 +26,10 @@ typeset -A PUMP
 typeset -A SYNC
 
 #find the local IP address (use the interface of the default route)
-if [[ $OS == "Linux" ]]
-then
+if [[ $OS == "Linux" ]]; then
 	default_dev=$(ip route list | sed 's/none //' | awk '/default/ {print $5}')
 	IP_addr=$(ip addr show dev $default_dev | awk '$1 == "inet" {print $2}' | head -1 | cut -d/ -f1)
-elif [[ $OS == "Darwin" ]]
-then
+elif [[ $OS == "Darwin" ]]; then
 	default_dev=$(netstat -rnf inet | awk '/^default/{print $NF}')
 	IP_addr=$(ipconfig getifaddr $default_dev)
 fi
@@ -66,13 +67,17 @@ function help {
 
 # touch files correspoinding to the versions that need to be installed so that the installer can install them
 function touchRPMs {
-	typeset version; typeset gwVers; typeset dshbVers; typeset pumpVers
-	typeset TIBvers; typeset syncVers; typeset oldFile
+	typeset version
+	typeset gwVers
+	typeset dshbVers
+	typeset pumpVers
+	typeset TIBvers
+	typeset syncVers
+	typeset oldFile
 	typeset assetDir="$SCRIPTDIR"/assets
 	typeset rpmDir="$assetDir"/rpms/tyk
 	version=$1
-	if [[ ${GATEWAY[$version]+_} ]]
-	then
+	if [[ ${GATEWAY[$version]+_} ]]; then
 		gwVers=${GATEWAY[$version]}
 		dshbVers=${DASHBOARD[$gwVers]}
 		TIBvers=${TIB[$gwVers]}
@@ -83,37 +88,32 @@ function touchRPMs {
 		exit 1
 	fi
 	# get the schema file
-	if [[ -f "$assetDir/schema.json" ]]
-	then
+	if [[ -f "$assetDir/schema.json" ]]; then
 		\rm -f "$assetDir/schema.json"
 	fi
 	wget -q https://raw.githubusercontent.com/TykTechnologies/tyk/v$version/cli/linter/schema.json -O "$assetDir/schema.json"
 	# remove the existing install files so we can create new ones
-	for oldFile in "$rpmDir"/tyk-gateway-* "$rpmDir"/tyk-dashboard-* "$rpmDir"/tyk-pump-* "$rpmDir"/tyk-identity-broker-* "$rpmDir"/tyk-sync-*
-	do
-		if [[ -f "$oldFile" ]]
-		then
+	for oldFile in "$rpmDir"/tyk-gateway-* "$rpmDir"/tyk-dashboard-* "$rpmDir"/tyk-pump-* "$rpmDir"/tyk-identity-broker-* "$rpmDir"/tyk-sync-*; do
+		if [[ -f "$oldFile" ]]; then
 			rm -f "$oldFile"
 		fi
 	done
 	touch "$rpmDir/tyk-gateway-$gwVers"
 	touch "$rpmDir/tyk-dashboard-$dshbVers"
 	touch "$rpmDir/tyk-pump-$pumpVers"
-	if [[ -n $TIBvers ]]
-	then
+	if [[ -n $TIBvers ]]; then
 		touch "$rpmDir/tyk-identity-broker-$TIBvers"
 	fi
-	if [[ -n $syncVers ]]
-	then
+	if [[ -n $syncVers ]]; then
 		touch "$rpmDir/tyk-sync-$syncVers"
 	fi
 }
 
 # list the version relationships we know about
 function listVersions {
-	typeset gwVers; typeset version
-	for version in $(echo ${!GATEWAY[@]} | xargs -n 1 | sort -rV)
-	do
+	typeset gwVers
+	typeset version
+	for version in $(echo ${!GATEWAY[@]} | xargs -n 1 | sort -rV); do
 		gwVers=${GATEWAY[$version]}
 		echo "Version:   $version"
 		echo "    Gateway:   $gwVers"
@@ -125,8 +125,14 @@ function listVersions {
 
 # isolated to keep IFS from leaking
 function loadVersions {
-	typeset line; typeset IFS; typeset gwVers; typeset dshbVers; typeset pumpVers
-	typeset TIBvers; typeset syncVers; typeset version
+	typeset line
+	typeset IFS
+	typeset gwVers
+	typeset dshbVers
+	typeset pumpVers
+	typeset TIBvers
+	typeset syncVers
+	typeset version
 	line=$1
 	IFS=,
 	echo "$line" | read version gwVers dshbVers pumpVers TIBvers syncVers
@@ -139,9 +145,9 @@ function loadVersions {
 
 # Load the versions of the products that go together
 function loadVersionFile {
-	typeset line; typeset versionFile
-	for line in $(awk 'NF && !/#/' $VERSIONFILE)
-	do
+	typeset line
+	typeset versionFile
+	for line in $(awk 'NF && !/#/' $VERSIONFILE); do
 		loadVersions "$line"
 	done
 }
@@ -161,8 +167,7 @@ function getAllSandboxInfo {
 	typeset existing
 	typeset index
 	existing=$(docker container list -a | awk '$NF ~ /^sandbox-/ {print $NF}' | cut -d \- -f2 | sort -n)
-	for index in $existing
-	do
+	for index in $existing; do
 		getSandboxInfo $index
 	done
 }
@@ -173,8 +178,7 @@ function latestImageRev {
 	typeset existing
 	version=$1
 	existing=$(docker image list tyk-sandbox | awk '$2 ~ /'$version'/ {print $2}' | sort -V | tail -1)
-	if [[ ! -z $existing ]]
-	then
+	if [[ ! -z $existing ]]; then
 		echo $existing | cut -d- -f2
 	fi
 }
@@ -186,8 +190,7 @@ function nextFreeImageRev {
 	typeset biggest
 	version=$1
 	existing=$(latestImageRev $version)
-	if [[ -z $existing ]]
-	then
+	if [[ -z $existing ]]; then
 		echo 1
 	else
 		biggest=$(echo $existing | cut -d- -f2)
@@ -201,11 +204,9 @@ function nextFreeContainer {
 	typeset existing
 	typeset i
 	existing=$(docker container list -a | awk '$NF ~ /^sandbox-/ {print $NF}')
-	for i in $(seq 1 1000) 
-	do
+	for i in $(seq 1 1000); do
 		test="sandbox-$i"
-		if ! echo $existing | grep -qw $test
-		then
+		if ! echo $existing | grep -qw $test; then
 			echo $i
 			break
 		fi
@@ -215,8 +216,7 @@ function nextFreeContainer {
 # build all images
 function buildAllImages {
 	typeset version
-	for version in $(echo ${!GATEWAY[@]} | xargs -n 1 | sort -rV)
-	do
+	for version in $(echo ${!GATEWAY[@]} | xargs -n 1 | sort -rV); do
 		echo "[INFO]Building $version"
 		buildImage -v $version
 	done
@@ -224,40 +224,41 @@ function buildAllImages {
 
 # invoke docker image build with all the right details
 function buildImage {
-	typeset arg; typeset tykVersion; typeset tykVersion
-	typeset rpm; typeset packageRev; typeset arg; typeset OPTARG
-	while getopts :lv:r: arg
-	do
-		case $arg in 
-			l)
-				listVersions
-				exit 0
-				;;
-			v)
-				tykVersion=$OPTARG
-				;;
-			:)
-				echo "Option -$OPTARG requires an arguement."
-				exit 1
-				;;
-			\?)
-				echo "Invalid option: -$OPTARG"
-				exit 1
-				;;
+	typeset arg
+	typeset tykVersion
+	typeset tykVersion
+	typeset rpm
+	typeset packageRev
+	typeset arg
+	typeset OPTARG
+	while getopts :lv:r: arg; do
+		case $arg in
+		l)
+			listVersions
+			exit 0
+			;;
+		v)
+			tykVersion=$OPTARG
+			;;
+		:)
+			echo "Option -$OPTARG requires an arguement."
+			exit 1
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG"
+			exit 1
+			;;
 		esac
 	done
-	if [[ -z $tykVersion ]]
-	then
+	if [[ -z $tykVersion ]]; then
 		echo "[FATAL]Must specify a version to build" 1>&2
 		exit 1
-	elif [[ $tykVersion == "ALL" ]]
-	then
+	elif [[ $tykVersion == "ALL" ]]; then
 		buildAllImages
 		return
 	fi
-	packageRev=$( nextFreeImageRev $tykVersion )
-	if ! docker image list tbi | grep -qw latest
-	then
+	packageRev=$(nextFreeImageRev $tykVersion)
+	if ! docker image list tbi | grep -qw latest; then
 		cd "$SCRIPTDIR/tbi"
 		docker image build --tag tbi:latest .
 	fi
@@ -268,108 +269,95 @@ function buildImage {
 
 # invoke docker container create and start with everything set
 function createSandbox {
-	typeset index; typeset list; typeset ticket; typeset imageVersion; typeset env_file
-	typeset containerName; typeset arg; typeset offset; typeset hostFQDN; typeset dashboardPort; typeset gatewayPort
-	typeset label; typeset dashboardURL; typeset gatewayURL; typeset TIBPort; typeset tibURL; typeset noBootstrap
-	typeset arg; typeset OPTARG; typeset redisPort; typeset mongoPort
-	while getopts :ni:v:t:l: arg
-	do
+	typeset index; typeset list; typeset ticket; typeset imageVersion; typeset env_file; typeset containerName
+	typeset arg; typeset offset; typeset hostFQDN; typeset dashboardPort; typeset gatewayPort; typeset label
+	typeset dashboardURL; typeset gatewayURL; typeset TIBPort; typeset tibURL; typeset noBootstrap; typeset arg
+	typeset OPTARG; typeset redisPort; typeset mongoPort
+	while getopts :ni:v:t:l: arg; do
 		case $arg in
-			i)
-				index=$OPTARG
-				;;
-			n)
-				noBootstrap=1
-				;;
-			t)
-				ticket="$OPTARG"
-				;;
-			v)
-				imageVersion=$OPTARG
-				;;
-			l)
-				logLevel=$OPTARG
-				if [[ $logLevel != "debug" && $logLevel != "warn" && $logLevel != "error" ]]
-				then
-					echo "loglevel must be one of 'debug', 'warn', 'error'"
-					exit 1
-				fi
-				;;
-			:)
-				echo "Option -$OPTARG requires an arguement."
+		i)
+			index=$OPTARG
+			;;
+		n)
+			noBootstrap=1
+			;;
+		t)
+			ticket="$OPTARG"
+			;;
+		v)
+			imageVersion=$OPTARG
+			;;
+		l)
+			logLevel=$OPTARG
+			if [[ $logLevel != "debug" && $logLevel != "warn" && $logLevel != "error" ]]; then
+				echo "loglevel must be one of 'debug', 'warn', 'error'"
 				exit 1
-				;;
-			\?)
-				echo "Invalid option: -$OPTARG"
-				exit 1
-				;;
+			fi
+			;;
+		:)
+			echo "Option -$OPTARG requires an arguement."
+			exit 1
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG"
+			exit 1
+			;;
 		esac
 	done
 
-	if [[ -z $imageVersion ]]
-	then
+	if [[ -z $imageVersion ]]; then
 		imageVersion=latest
 		echo "[FATAL]Must specify a tyk-sandbox version"
 		exit 1
 	fi
-	if ! echo $imageVersion | grep -q -- - 
-	then
+	if ! echo $imageVersion | grep -q -- -; then
 		imageVersion=$imageVersion-$(latestImageRev $imageVersion)
 	fi
-	if ! docker image inspect tyk-sandbox:$imageVersion > /dev/null 2>&1
-	then
+	if ! docker image inspect tyk-sandbox:$imageVersion >/dev/null 2>&1; then
 		echo "[WARN]tyk-sandbox:$imageVersion does not exist. Did you intend to 'build' an image not 'create' a container?"
 		exit 1
 	fi
 
-	if [[ -z $logLevel ]]
-	then
+	if [[ -z $logLevel ]]; then
 		logLevel="debug"
 	fi
 
-	if [[ -z $ticket ]]
-	then
+	if [[ -z $ticket ]]; then
 		ticket="N/A"
 	fi
 
-	if [[ -z $index ]]
-	then
+	if [[ -z $index ]]; then
 		index=$(nextFreeContainer)
 	fi
 
-	offset=$(($index-1))
+	offset=$(($index - 1))
 	hostFQDN=$IP_addr
-	dashboardPort=$(($DashboardBasePort+$offset))
-	gatewayPort=$(($GatewayBasePort+$offset))
-	redisPort=$(($RedisBasePort+$offset))
-	mongoPort=$(($MongoBasePort+$offset))
+	dashboardPort=$(($DashboardBasePort + $offset))
+	gatewayPort=$(($GatewayBasePort + $offset))
+	redisPort=$(($RedisBasePort + $offset))
+	mongoPort=$(($MongoBasePort + $offset))
 	containerName=sandbox-$index
 	label=$containerName
 	dashboardURL=http://$hostFQDN:$dashboardPort/
 	gatewayURL=https://$hostFQDN:$gatewayPort/
 	# only configure TIB if gateway version is in the 2 series
-	if echo $imageVersion | egrep -q '^2'
-	then
-		TIBPort="--publish $(($TIBBasePort+$offset)):3010"
-		tibURL="--label sandbox.tiburl=http://$hostFQDN:$(($TIBBasePort+$offset))/"
+	if echo $imageVersion | egrep -q '^2'; then
+		TIBPort="--publish $(($TIBBasePort + $offset)):3010"
+		tibURL="--label sandbox.tiburl=http://$hostFQDN:$(($TIBBasePort + $offset))/"
 	fi
 	# Create a directory just for this version to hold plugins
-	for dir in "$SandboxPluginDir" "$SandboxCertDir"
-	do
-		if [[ ! -d "$dir" ]]
-		then
+	for dir in "$SandboxPluginDir" "$SandboxCertDir"; do
+		if [[ ! -d "$dir" ]]; then
 			mkdir -p "$dir"
 		fi
 	done
-	if [[ $imageVersion != "latest" && ! -d $SandboxPluginDir/$imageVersion ]]
-	then
+	if [[ $imageVersion != "latest" && ! -d $SandboxPluginDir/$imageVersion ]]; then
 		echo "[WARN]Creating $SandboxPluginDir/$imageVersion: It will be empty"
 		mkdir -p $SandboxPluginDir/$imageVersion
 	fi
 	# load username, password and licence if they stored in ~/.tyk-sandbox
 	# varaible names are SBX_LICENSE, SBX_USER, SBX_PASSWORD
-	if [[ -z $noBootstrap && -f ~/.tyk-sandbox ]]
-	then
+	if [[ -z $noBootstrap && -r ~/.tyk-sandbox ]]; then
 		env_file="--env-file $(\ls ~/.tyk-sandbox)"
 	else
 		env_file=""
@@ -399,8 +387,7 @@ function createSandbox {
 		--volume $SandboxPluginDir/$imageVersion:/opt/tyk-plugins \
 		tyk-sandbox:$imageVersion
 	# --volume $SandboxCertDir:/opt/tyk-certificates
-	if [[ $? -eq 0 ]]
-	then
+	if [[ $? -eq 0 ]]; then
 		echo "[INFO]Starting container $containerName"
 		docker container start $containerName
 		getSandboxInfo $index
@@ -409,15 +396,13 @@ function createSandbox {
 
 # list the sandboxes in a standard format.
 function listNames {
-	typeset name; typeset list
-	if [[ $1 == "ALL" ]]
-	then
+	typeset name
+	typeset list
+	if [[ $1 == "ALL" ]]; then
 		docker container list -a | awk '$NF ~ /^sandbox-/ {print $NF}' | cut -d \- -f2 | sort -n
 	else
-		for name in $*
-		do
-			if echo $name | grep -iq sandbox-
-			then
+		for name in $*; do
+			if echo $name | grep -iq sandbox-; then
 				name=$(echo $name | cut -d\- -f2)
 			fi
 			list="$list $name"
@@ -426,8 +411,7 @@ function listNames {
 	fi
 }
 
-if [[ $# -lt 1 ]]
-then
+if [[ $# -lt 1 ]]; then
 	help
 	exit 1
 fi
@@ -436,55 +420,52 @@ fi
 loadVersionFile
 
 case $1 in
-	rm|stop|start|restart)
-		action=$1
+rm | stop | start | restart)
+	action=$1
+	shift
+	for index in $(listNames $*); do
+		docker container $action sandbox-$index
+	done
+	;;
+build)
+	shift
+	# Create a docker image with the given parameters
+	buildImage "$@"
+	;;
+create)
+	shift
+	# Create a docker sandbox with the given parameters
+	createSandbox "$@"
+	;;
+info | list | status)
+	if [[ $# -gt 1 ]]; then
 		shift
-		for index in $(listNames $*)
-		do
-			docker container $action sandbox-$index
+		# Inspect the details of the given container
+		for index in $(listNames $*); do
+			getSandboxInfo $index
 		done
-		;;
-	build)
-		shift
-		# Create a docker image with the given parameters
-		buildImage "$@"
-		;;
-	create)
-		shift
-		# Create a docker sandbox with the given parameters
-		createSandbox "$@"
-		;;
-	info|list|status)
-		if [[ $# -gt 1 ]]
-		then
-			shift
-			# Inspect the details of the given container
-			for index in $(listNames $*)
-			do
-				getSandboxInfo $index
-			done
-		else
-			# Inspect the details of all exiting containers
-			getAllSandboxInfo
-		fi
-		;;
-	shell|bash)
-		# Give a shell in the given container
-		shift
-		for index in $(listNames $*)
-		do
-			docker container exec -it sandbox-$index bash
-		done
-		;;
-	image*)
-		# list the tyk-sandbox docker images
-		# note the almost magical pipe feature of awk used here. It sorts the versions but not the header
-		docker image list tyk-sandbox | awk '/REPOSITORY/ {print $0; next} {print $0 | "sort -Vr"}'
-		;;
-	help)
-		help
-		;;
-	*)
-		echo "[FATAL]Unknown option \"$1\"" 1>&2
-		help
+	else
+		# Inspect the details of all exiting containers
+		getAllSandboxInfo
+	fi
+	;;
+shell | bash)
+	# Give a shell in the given container
+	shift
+	for index in $(listNames $*); do
+		docker container exec -it sandbox-$index bash
+	done
+	;;
+image*)
+	# list the tyk-sandbox docker images
+	# note the almost magical pipe feature of awk used here. It sorts the versions but not the header
+	docker image list tyk-sandbox | awk '/REPOSITORY/ {print $0; next} {print $0 | "sort -Vr"}'
+	;;
+help)
+	help
+	;;
+*)
+	echo "[FATAL]Unknown option \"$1\"" 1>&2
+	help
+	;;
 esac
