tbi/baseOS/os-setup: open redis configs to the world

diff --git a/tbi/baseOS/os-setup b/tbi/baseOS/os-setup
--- a/tbi/baseOS/os-setup
+++ b/tbi/baseOS/os-setup
@@ -48,10 +48,22 @@ if grep -q 'release 8' /etc/redhat-release; then
 	yum -y install logrotate make openssl mongodb-org redis
 fi
 
-# open redis and mongo up to the world! Beware!!!
+# open mongo up to the world! Beware!!!
 sed -i 's/bindIp/#bindIp/' /etc/mongod.conf
-sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis.conf
-sed -i 's/^bind 127.0.0.1/#bind 127.0.0.1/' /etc/redis.conf
+
+# find the redis config file
+if [[ -f /etc/redis.conf ]]; then
+	REDIS_CONFIG=/etc/redis.conf
+elif [[ -f /etc/redis/redis.conf ]]; then
+	REDIS_CONFIG=/etc/redis/redis.conf
+else
+	echo "[FATAL]Cannot find redis config file. Checked /etc/redis.conf and /etc/redis/redis.conf but didn't find them"
+	exit 1
+fi
+
+# open redis up to the world! Beware!!!
+sed -i 's/^protected-mode yes/protected-mode no/' $REDIS_CONFIG
+sed -i 's/^bind 127.0.0.1/#bind 127.0.0.1/' $REDIS_CONFIG
 
 # tidyup to reduce the image size. Saves 200-300 MB
 # removed to speed up next stage
