dump-redis: better printing of zset scores

diff --git a/scripts/dump-redis b/scripts/dump-redis
--- a/scripts/dump-redis
+++ b/scripts/dump-redis
@@ -6,49 +6,82 @@
 
 PATH=/scripts:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH
 
-PORT=6379
-REDIS_KEY_PATTERN="${1:-*}"
+PORT=''
+HOST=''
+PATTERN='*'
+while getopts :a:p:h: arg; do
+  case $arg in
+    h)
+      HOST=$OPTARG
+      ;;
+    p)
+      PORT=$OPTARG
+      ;;
+    a)
+      export REDISCLI_AUTH="$OPTARG"
+      ;;
+    :)
+      echo "[FATAL]Option -$OPTARG requires an arguement."
+      exit 1
+      ;;
+    \?)
+      echo "[FATAL]Invalid option: -$OPTARG"
+      exit 1
+      ;;
+  esac
+done
+if [[ -z $HOST || -z $PORT ]]; then
+  echo "[FATAL]Usage $0 -p <port> -h <hostname or IP> -a password"
+  exit 1
+else
+  # remove the first 4 commandline arguments to leave the remaining patterns to search for
+  shift 4
+fi
+if [[ ! -z $REDISCLI_AUTH ]]; then
+  # remove the next 2 commandline arguments to leave the remaining patterns to search for
+  shift 2
+fi
+
 function dumpRedis {
   typeset REDIS_KEY_PATTERN
   REDIS_KEY_PATTERN="$1"
-  for key in $(redis-cli -p $PORT --scan --pattern "$REDIS_KEY_PATTERN" | sort); do
-    type=$(redis-cli -p $PORT type $key)
-    ttl=$(redis-cli -p $PORT ttl $key)
+  for key in $(redis-cli -h $HOST -p $PORT --scan --pattern "$REDIS_KEY_PATTERN" | sort); do
+    type=$(redis-cli -h $HOST -p $PORT type $key)
+    ttl=$(redis-cli -h $HOST -p $PORT ttl $key)
     echo -n "$key (type:$type) (ttl:$ttl) => "
     case $type in
-    list)
-      echo
-      redis-cli -p $PORT lrange $key 0 -1 | sed 's/^/  /'
-      ;;
-    hash)
-      redis-cli -p $PORT hgetall $key | sed 's/^/  /'
-      ;;
-    set)
-      redis-cli -p $PORT smembers $key
-      ;;
-    zset)
-      echo
-      redis-cli -p $PORT zrange $key 0 -1 withscores | sed 's/^/  /'
-      ;;
-    string)
-      if redis-cli -p $PORT get $key | egrep -q '^{'; then
-        redis-cli -p $PORT get $key | jq .
-      else
-        redis-cli -p $PORT get $key
-      fi
-      ;;
-    *)
-      echo "[WARN]Unknown type $type"
-      redis-cli -p $PORT get $key
-      ;;
+      list)
+        echo
+        redis-cli -h $HOST -p $PORT lrange $key 0 -1 | sed 's/^/  /'
+        ;;
+      hash)
+        redis-cli -h $HOST -p $PORT hgetall $key | sed 's/^/  /'
+        ;;
+      set)
+        redis-cli -h $HOST -p $PORT smembers $key
+        ;;
+      zset)
+        echo
+        redis-cli -h $HOST -p $PORT zrange $key 0 -1 withscores | sed 's/^/  /' | awk '/-/ {printf("%s =>  ", $NF)} !/-/ {print $NF}'
+        ;;
+      string)
+        if redis-cli -h $HOST -p $PORT get $key | egrep -q '^{'; then
+          redis-cli -h $HOST -p $PORT get $key | jq .
+        else
+          redis-cli -h $HOST -p $PORT get $key
+        fi
+        ;;
+      *)
+        echo "[WARN]Unknown type $type"
+        redis-cli -h $HOST -p $PORT get $key
+        ;;
     esac
   done
 }
 
-if [[ $# -lt 1 ]]; then
-  dumpRedis '*'
-else
-  for pattern in "$@"; do
-    dumpRedis "$pattern"
-  done
-fi
+dumpRedis "${1:-*}"
+shift
+
+for pattern in "$@"; do
+  dumpRedis "$pattern"
+done
